// Keep NativeWind's CSS variables aligned with the persisted theme's native tokens.
const fs = require('fs');
const source = fs.readFileSync('constants/theme.ts', 'utf8');
const roles = {
  primary: 'primary', 'primary-foreground': 'primaryFg', card: 'surface',
  secondary: 'surface2', 'secondary-foreground': 'foreground', background: 'background',
  popover: 'surface', 'popover-foreground': 'foreground', muted: 'surface2',
  'muted-foreground': 'mutedFg', destructive: 'accentRed', foreground: 'foreground',
  border: 'border', input: 'surface3', ring: 'primary', accent: 'primaryMuted',
  'accent-foreground': 'foreground', mint: 'accentEmerald', amber: 'accentAmber',
};
const palette = name => {
  const body = source.match(new RegExp(`export const ${name} = \\{([\\s\\S]*?)\\};`))[1];
  return Object.fromEntries([...body.matchAll(/(\w+):\s*'([^']+)'/g)].map(m => [m[1], m[2]]));
};
const declarations = colors => Object.entries(roles).map(([role, key]) => {
  let color = colors[key];
  if (color.startsWith('#')) color = [1, 3, 5].map(i => parseInt(color.slice(i, i + 2), 16)).join(' ');
  else color = color.match(/[\d.]+/g).slice(0, 3).join(' ');
  return `    --${role}: ${color};`;
}).join('\n');
const light = declarations(palette('LightTheme'));
const dark = declarations(palette('DarkTheme'));
fs.writeFileSync('globals.css', `/* Generated by npm run theme:generate from constants/theme.ts. */
@import "tailwindcss/theme.css" layer(theme);
@import "tailwindcss/preflight.css" layer(base);
@import "tailwindcss/utilities.css";
@import "nativewind/theme";
@layer theme {
  :root {\n${light}\n  }
  @media (prefers-color-scheme: dark) { :root {\n${dark}\n  } }
  :root.dark {\n${dark}\n  }
  :root.light {\n${light}\n  }
}
@theme inline {
${Object.keys(roles).map(role => `  --color-${role}: rgb(var(--${role}));`).join('\n')}
}
`);
